Controllers/BelongController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using doancuoiky.Models;

namespace doancuoiky.Controllers
{
    public class BelongController : Controller
    {
        public IActionResult Xoa(int qid, int mcid) {
            StoreContext context = HttpContext.RequestServices.GetService(typeof(doancuoiky.Models.StoreContext)) as StoreContext;
            int err = context.xoaBelong(qid, mcid);
            if (err != -1) {
                return RedirectToAction("Update", "Quiz", new {mcid = mcid});
            }
            else {
                return View();
            }
        }
    }
}

Controllers/QuizController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using doancuoiky.Models;

namespace doancuoiky.Controllers
{
    public class QuizController : Controller
    {
        public IActionResult Index() {
            ViewData["css_path"] = "/css/Quiz/Index.css";
            StoreContext context = HttpContext.RequestServices.GetService(typeof(doancuoiky.Models.StoreContext)) as StoreContext;
            return View(context.getMultiplechoices(AuthController.uid));
        }

        public IActionResult ThemQuiz(string title, string description, int time, int[] qids) {
            ViewData["css_path"] = "/css/Quiz/ThemQuiz.css";
            StoreContext context = HttpContext.RequestServices.GetService(typeof(doancuoiky.Models.StoreContext)) as StoreContext;
            int mcid = context.addQuiz(title, description, time, AuthController.uid);
            if (mcid > 0) {
                int err = context.addBelong(qids, mcid);
                if (err != -1) {
                    return RedirectToAction("Index", "Home");
                }
                else {
                    return View();
                }
            }
            return View();
        }

        public IActionResult Delete(int mcid) {
            StoreContext context = HttpContext.RequestServices.GetService(typeof(doancuoiky.Models.StoreContext)) as StoreContext;
            int err = context.xoaQuiz(mcid);
            if (err != -1) {
                return RedirectToAction("Index", "Quiz");
            }
            else {
                return View();
            }
        }

        public IActionResult Update(int mcid) {
            ViewData["css_path"] = "/css/Quiz/Update.css";
            StoreContext context = HttpContext.RequestServices.GetService(typeof(doancuoiky.Models.StoreContext)) as StoreContext;
            return View(context.getMultiplechoice(mcid));
        }

        public IActionResult Sua(int id, string title, string description, int time) {
            StoreContext context = HttpContext.RequestServices.GetService(typeof(doancuoiky.Models.StoreContext)) as StoreContext;
            int err = context.capnhatQuiz(id, title, description, time);
            if (err != -1) {
                return RedirectToAction("Index", "Quiz");
            }
            else {
                return View();
            }
        }
    }
}

Views/Quiz/Delete.cshtml
<@{
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}

<script>
    alert("Lỗi không xóa không được");
    window.location.href = '@Url.Action("Index", "Quiz")';
</script>

Views/Quiz/Index.cshtml
@{
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}
@model List<Multiplechoice>
<section class="home-section">
  <div class="hs__header" style="display: none;">
    <div class="filter">
      <select class="filter-content" id="selected_filter_item">
        <optgroup label="Lớp 10">
          <option value="toan10">Toán 10</option>
          <option value="vatly10">Vật lý 10</option>
          <option value="hoahoc10">Hóa học 10</option>
          <option value="sinhoc10">Sinh học 10</option>
          <option value="anhvan10">Anh văn 10</option>
          <option value="gdcd">Giáo dục công dân 10</option>
          <option value="dialy">Địa lý 10</option>
          <option value="lichsu">Lịch sử 10</option>
        </optgroup>
        <optgroup label="Lớp 11">
          <option value="toan10">Toán 11</option>
          <option value="vatly10">Vật lý 11</option>
          <option value="hoahoc10">Hóa học 11</option>
          <option value="sinhoc10">Sinh học 11</option>
          <option value="anhvan10">Anh văn 11</option>
          <option value="gdcd">Giáo dục công dân 11</option>
          <option value="dialy">Địa lý 11</option>
          <option value="lichsu">Lịch sử 11</option>
        </optgroup>
        <optgroup label="Lớp 12">
          <option value="toan10">Toán 12</option>
          <option value="vatly10">Vật lý 12</option>
          <option value="hoahoc10">Hóa học 12</option>
          <option value="sinhoc10">Sinh học 12</option>
          <option value="anhvan10">Anh văn 12</option>
          <option value="gdcd">Giáo dục công dân 12</option>
          <option value="dialy">Địa lý 12</option>
          <option value="lichsu">Lịch sử 12</option>
        </optgroup>
        <optgroup label="Ôn thi THPT">
          <option value="toan10">Toán</option>
          <option value="vatly10">Vật lý</option>
          <option value="hoahoc10">Hóa học</option>
          <option value="sinhoc10">Sinh học</option>
          <option value="anhvan10">Anh văn</option>
          <option value="gdcd">Giáo dục công dân</option>
          <option value="dialy">Địa lý</option>
          <option value="lichsu">Lịch sử</option>
        </optgroup>
      </select>
    </div>
    <div class="searchbox">
      <form>
        <input id="tf_search" type="text" name="" placeholder="Nhập nội dung của bạn đi nào..." />
        <input id="btn_search" type="submit" name="" value="Tìm ngay" />
      </form>
    </div>
  </div>
  <div class="hs__content row">
      <h3 class="grid-subject-title">CÁC BÀI TRẮC NGHIỆM CỦA TÔI</h3>
      <div class="grid-container">
        @foreach (var item in Model)
        {
          <div class="grid-item">
            <div class="quiz-name">
                <h3>@item.title</h3>
            </div>
            <div class="quiz-content">
                <div class="quiz-channel">
                    <p>Số câu hỏi: <b>@item.total câu</b></p>
                </div>
                <div class="quiz-action">
                    <button onclick="sua(@item.id)">Sửa</button>
                    <button onclick="xoa(@item.id)">Xóa</button>
                </div>
                <div class="quiz-descr">
                    <p>
                    <span>Thời lượng</span><br />
                    <span>@item.time phút</span>
                    </p>
                    <p>
                    <span>Tham gia</span><br />
                    <span>@item.participant</span>
                    </p>
                </div>
            </div>
          </div>
        }
      </div>
  </div>
</section>

<script type="text/javascript" src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
<script type="text/javascript" src="https://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

<script>
  function xoa(id) {
    if (confirm("Xóa bài trắc nghiệm?")) {
        window.location.href = '@Url.Action("Delete", "Quiz")?mcid=' + id;
    }
  }

  function sua(id) {
    if (confirm("Sửa bài trắc nghiệm?")) {
        window.location.href = '@Url.Action("Update", "Quiz")?mcid=' + id;
    }
  }
</script>

Views/Quiz/Sua.cshtml
<@{
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}

<script>
    alert("Lỗi update được quiz");
    window.location.href = '@Url.Action("Index", "Question")';
</script>

Views/Quiz/ThemQuiz.cshtml
<@{
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}

<script>
    alert("Lỗi không thêm được");
    window.location.href = '@Url.Action("Index", "Question")';
</script>

Views/Quiz/Update.cshtml
@{
    Layout = "~/Views/Shared/_LayoutHome.cshtml";
}
@model List<Multiplechoice>

@foreach (var item in Model)
{
    <section class="home-section">
    <div class="container">
    <form id="myform" action="/Quiz/Sua" method="post">
        <input type="text" id="id" name="id" value='@item.id' hidden>
        <div class="row">
        <div class="col-25">
            <label>Title</label>
        </div>
        <div class="col-75">
            <input type="text" name="title" placeholder="Nhập tên quiz" value="@item.title">
        </div>
        </div>
        <div class="row">
        <div class="col-25">
            <label>Description</label>
        </div>
        <div class="col-75">
            <textarea name="description" placeholder="Nhập miêu tả" style="height:200px">@item.description</textarea>
        </div>
        </div>
        <div class="row">
        <div class="col-25">
            <label>Thời gian làm bài</label>
        </div>
        <div class="col-75">
            <input id="time" type="text" name="time" min="1" max="360" placeholder="Nhập thời gian từ 1 phút tới 360 phút" value="@item.time">
        </div>
        </div>
        <div id="questions" class="row">
        </div>
        <div class="row">
        <input id="btn" type="submit" value="Sửa bài trắc nghiệm">
        </div> 
    </form>
    </div>
    </section>
}


<script>
$(function () {
  $("#time").keydown(function () {
    // Save old value.
    if (!$(this).val() || (parseInt($(this).val()) <= 360 && parseInt($(this).val()) >= 1))
    $(this).data("old", $(this).val());
  });
  $("#time").keyup(function () {
    // Check correct, else revert back to old value.
    if (!$(this).val() || (parseInt($(this).val()) <= 360 && parseInt($(this).val()) >= 1))
      ;
    else
      $(this).val($(this).data("old"));
  });
});

var mcid = $(document).find("#id").val();
$.ajax({
    url: '@Url.Action("getQuestions","Question")',
    method: 'post',
    dataType: 'json',
    data: {
        mcid: mcid
    },
    success: function(result) {
        
        $("#questions").html("");
        for (var i in result) {
            var html = '<div id="' + result[i].id + '" class="question_form" ondblclick="edit(this.id)">';
                html += '<span id="' + result[i].id + '" class="closebtn" onclick="xoa(this.id)">&times;</span>';
                html += '<h4 id="question">' + result[i].question + '</h4>';
                html += '<label id="A">A: ' + result[i].a + '</label> <br>';
                html += '<label id="B">B: ' + result[i].b + '</label> <br>';
                html += '<label id="C">C: ' + result[i].c + '</label> <br>';
                html += '<label id="D">D: ' + result[i].d + '</label> <br>';
                html += '<label id="answer">Đáp án: ' + result[i].answer + '</label>';
                html += '</div>';
            $("#questions").append(html);
        }
    }
});

function xoa(id) {
    if (confirm("Xóa câu hỏi?")) {
        window.location.href = '@Url.Action("Xoa", "Belong")?qid=' + id + '&mcid=' + mcid;
    }
}

function edit(id) {
    if (confirm("Chỉnh sửa câu hỏi?")) {
        window.location.href = '@Url.Action("Update", "Question")?qid=' + id;
    }
  }
</script>